/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.actividad3parte2;

/**
 *
 * @author Knoknozo
 */
public class VentanaPrincipal extends javax.swing.JFrame {
        boolean Circulo = false;
        boolean Cuadrado = false;
        boolean Rectangulo = false;
        boolean TrianguloRectangulo = false;
        boolean Rombo = false;
        boolean Trapecio = false;
    
    public VentanaPrincipal() {
        initComponents();
        TextoA.setVisible(false);
        TextoB.setVisible(false);
        TextoC.setVisible(false);
        TextoD.setVisible(false);
        BCalcular.setVisible(false);
        BBorrar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        Instrucciones = new javax.swing.JLabel();
        BSalir = new javax.swing.JButton();
        A = new javax.swing.JLabel();
        Area = new javax.swing.JLabel();
        Perimetro = new javax.swing.JLabel();
        BCalcular = new javax.swing.JButton();
        BBorrar = new javax.swing.JButton();
        B = new javax.swing.JLabel();
        TextoB = new javax.swing.JTextField();
        C = new javax.swing.JLabel();
        TextoC = new javax.swing.JTextField();
        D = new javax.swing.JLabel();
        TextoD = new javax.swing.JTextField();
        Hipotenusa = new javax.swing.JLabel();
        TipoTriangulo = new javax.swing.JLabel();
        Figura = new javax.swing.JLabel();
        TextoA = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        MCirculo = new javax.swing.JMenuItem();
        MCuadrado = new javax.swing.JMenuItem();
        MRectangulo = new javax.swing.JMenuItem();
        MTR = new javax.swing.JMenuItem();
        MRombo = new javax.swing.JMenuItem();
        MTrapecio = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Instrucciones.setText("haz click en \"Figura\" y elige la figura que quieras para calcular ");

        BSalir.setText("Salir");
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });

        BCalcular.setText("Calcular");
        BCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCalcularActionPerformed(evt);
            }
        });

        BBorrar.setText("Borrar");
        BBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBorrarActionPerformed(evt);
            }
        });

        TextoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCActionPerformed(evt);
            }
        });

        TextoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoAActionPerformed(evt);
            }
        });

        jMenu4.setText("Figura");

        MCirculo.setText("Circulo");
        MCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCirculoActionPerformed(evt);
            }
        });
        jMenu4.add(MCirculo);

        MCuadrado.setText("Cuadrado");
        MCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCuadradoActionPerformed(evt);
            }
        });
        jMenu4.add(MCuadrado);

        MRectangulo.setText("Rectangulo");
        MRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRectanguloActionPerformed(evt);
            }
        });
        jMenu4.add(MRectangulo);

        MTR.setText("Triangulo Rectangulo");
        MTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MTRActionPerformed(evt);
            }
        });
        jMenu4.add(MTR);

        MRombo.setText("Rombo");
        MRombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MRomboActionPerformed(evt);
            }
        });
        jMenu4.add(MRombo);

        MTrapecio.setText("Trapecio");
        MTrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MTrapecioActionPerformed(evt);
            }
        });
        jMenu4.add(MTrapecio);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(Instrucciones)
                .addContainerGap(318, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Hipotenusa)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Perimetro, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                .addComponent(Area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(A, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(B, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(C, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(D, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(TipoTriangulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TextoC, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(TextoB, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(TextoA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                            .addComponent(TextoD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 436, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BSalir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BBorrar)
                            .addComponent(BCalcular))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Figura)
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BBorrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(Figura)
                                .addGap(0, 54, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextoA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(A, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(Instrucciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 19, Short.MAX_VALUE)
                .addComponent(Area, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Perimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(BSalir)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Hipotenusa)
                        .addGap(18, 18, 18)
                        .addComponent(TipoTriangulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BSalirActionPerformed

    private void MCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCirculoActionPerformed
        // TODO add your handling code here:
        Circulo = true;
        Cuadrado = false;
        Rectangulo = false;
        TrianguloRectangulo = false;
        Rombo = false;
        Trapecio = false;
        BCalcular.setVisible(true);
        BBorrar.setVisible(true);
        Instrucciones.setVisible(false);
        A.setText("Radio");
        TextoA.setVisible(true);
        Area.setText("Area = ");
        Perimetro.setText("Perimetro = ");
        B.setText("");
        TextoB.setVisible(false);
        C.setText("");
        TextoC.setVisible(false);
        D.setText("");
        TextoD.setVisible(false);
        Hipotenusa.setText("");
        TipoTriangulo.setText("");
        Figura.setText("Circulo");
    }//GEN-LAST:event_MCirculoActionPerformed

    private void MCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCuadradoActionPerformed
        // TODO add your handling code here:
        Circulo = false;
        Cuadrado = true;
        Rectangulo = false;
        TrianguloRectangulo = false;
        Rombo = false;
        Trapecio = false;
        BCalcular.setVisible(true);
        BBorrar.setVisible(true);
        Instrucciones.setVisible(false);
        A.setText("Lado");
        TextoA.setVisible(true);
        Area.setText("Area = ");
        Perimetro.setText("Perimetro = ");
        B.setText("");
        TextoB.setVisible(false);
        C.setText("");
        TextoC.setVisible(false);
        D.setText("");
        TextoD.setVisible(false);
        Hipotenusa.setText("");
        TipoTriangulo.setText("");
        Figura.setText("Cuadrado");
    }//GEN-LAST:event_MCuadradoActionPerformed

    private void MRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRectanguloActionPerformed
        // TODO add your handling code here:
        Circulo = false;
        Cuadrado = false;
        Rectangulo = true;
        TrianguloRectangulo = false;
        Rombo = false;
        Trapecio = false;
        BCalcular.setVisible(true);
        BBorrar.setVisible(true);
        Instrucciones.setVisible(false);
        A.setText("Base");
        TextoA.setVisible(true);
        B.setText("Altura");
        TextoB.setVisible(true);
        Area.setText("Area = ");
        Perimetro.setText("Perimetro = ");
        C.setText("");
        TextoC.setVisible(false);
        D.setText("");
        TextoD.setVisible(false);
        Hipotenusa.setText("");
        TipoTriangulo.setText("");
        Figura.setText("Rectangulo");
    }//GEN-LAST:event_MRectanguloActionPerformed

    private void MTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MTRActionPerformed
        // TODO add your handling code here:
        Circulo = false;
        Cuadrado = false;
        Rectangulo = false;
        TrianguloRectangulo = true;
        Rombo = false;
        Trapecio = false;
        BCalcular.setVisible(true);
        BBorrar.setVisible(true);
        Instrucciones.setVisible(false);
        A.setText("base");
        TextoA.setVisible(true);
        B.setText("Altura");
        TextoB.setVisible(true);
        Area.setText("Area = ");
        Perimetro.setText("Perimetro = ");
        Hipotenusa.setText("Hipotenusa = ");
        TipoTriangulo.setText("Tipo de triangulo: ");
        C.setText("");
        TextoC.setVisible(false);
        D.setText("");
        TextoD.setVisible(false);
        Figura.setText("Triangulo Rectangulo");
    }//GEN-LAST:event_MTRActionPerformed

    private void MRomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MRomboActionPerformed
        // TODO add your handling code here:
        Circulo = false;
        Cuadrado = false;
        Rectangulo = false;
        TrianguloRectangulo = false;
        Rombo = true;
        Trapecio = false;
        BCalcular.setVisible(true);
        BBorrar.setVisible(true);
        Instrucciones.setVisible(false);
        A.setText("Lado");
        TextoA.setVisible(true);
        B.setText("Diagonal mayor");
        TextoB.setVisible(true);
        C.setText("Diagonal menor");
        TextoC.setVisible(true);
        Area.setText("Area = ");
        Perimetro.setText("Perimetro = ");
        D.setText("");
        TextoD.setVisible(false);
        Hipotenusa.setText("");
        TipoTriangulo.setText("");
        Figura.setText("Rombo");
    }//GEN-LAST:event_MRomboActionPerformed

    private void MTrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MTrapecioActionPerformed
        // TODO add your handling code here:
        Circulo = false;
        Cuadrado = false;
        Rectangulo = false;
        TrianguloRectangulo = false;
        Rombo = false;
        Trapecio = true;
        BCalcular.setVisible(true);
        BBorrar.setVisible(true);
        Instrucciones.setVisible(false);
        A.setText("Altura");
        TextoA.setVisible(true);
        B.setText("Lado");
        TextoB.setVisible(true);
        C.setText("Base Mayor");
        TextoC.setVisible(true);
        D.setText("Base Menor");
        TextoD.setVisible(true);
        Area.setText("Area = ");
        Perimetro.setText("Perimetro = ");
        Hipotenusa.setText("");
        TipoTriangulo.setText("");
        Figura.setText("Trapecio");
    }//GEN-LAST:event_MTrapecioActionPerformed

    private void BBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBorrarActionPerformed
        // TODO add your handling code here:
        if(Circulo){
            TextoA.setText("");
            Area.setText("Area = ");
            Perimetro.setText("Perimetro = ");
        }
        else if(Cuadrado){
            TextoA.setText("");
            Area.setText("Area = ");
            Perimetro.setText("Perimetro = ");
        }
        else if(Rectangulo){
            TextoA.setText("");
            TextoB.setText("");
            Area.setText("Area = ");
            Perimetro.setText("Perimetro = ");
        }
        else if(TrianguloRectangulo){
            TextoA.setText("");
            TextoB.setText("");
            Area.setText("Area = ");
            Perimetro.setText("Perimetro = ");
            Hipotenusa.setText("Hipotenusa = ");
            TipoTriangulo.setText("Tipo de triangulo: ");
        }
        else if(Rombo){
            TextoA.setText("");
            TextoB.setText("");
            TextoC.setText("");
            Area.setText("Area = ");
            Perimetro.setText("Perimetro = ");
        }
        else{
            TextoA.setText("");
            TextoB.setText("");
            TextoC.setText("");
            TextoD.setText("");
            Area.setText("Area = ");
            Perimetro.setText("Perimetro = ");
        }
    }//GEN-LAST:event_BBorrarActionPerformed

    private void BCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCalcularActionPerformed
        // TODO add your handling code here:
        int radio,lado,base,altura,Bmayor,Bmenor,Dmayor,Dmenor;
        double area, perimetro,hipotenusa;
        if (Circulo){
            radio = Integer.parseInt(TextoA.getText());
            area = CCirculo.CalcularArea(radio);
            perimetro = CCirculo.CalcularPerimetro(radio);
            Area.setText("Area = "+String.valueOf(area));
            Perimetro.setText("Perimetro = "+String.valueOf(perimetro));
        }
        else if (Cuadrado){
            lado = Integer.parseInt(TextoA.getText());
            area = CCuadrado.CalcularArea(lado);
            perimetro = CCuadrado.CalcularPerimetro(lado);
            Area.setText("Area = "+String.valueOf(area));
            Perimetro.setText("Perimetro = "+String.valueOf(perimetro));
        }
        else if(Rectangulo){
            base = Integer.parseInt(TextoA.getText());
            altura = Integer.parseInt(TextoB.getText());
            area = CRectangulo.CalcularArea(base, altura);
            perimetro = CRectangulo.CalcularPerimetro(base, altura);
            Area.setText("Area = "+String.valueOf(area));
            Perimetro.setText("Perimetro = "+String.valueOf(perimetro));
        }
        else if (TrianguloRectangulo){
            base = Integer.parseInt(TextoA.getText());
            altura = Integer.parseInt(TextoB.getText());
            area = CTrianguloRectangulo.CalcularArea(base, altura);
            perimetro = CTrianguloRectangulo.CalcularPerimetro(base, altura);
            hipotenusa = CTrianguloRectangulo.CalcularHipotenusa(base, altura);
            Area.setText("Area = "+String.valueOf(area));
            Perimetro.setText("Perimetro = "+String.valueOf(perimetro));
            Hipotenusa.setText("Hipotenusa = "+String.valueOf(hipotenusa));
            TipoTriangulo.setText(CTrianguloRectangulo.DeterminarTipoTriangulo(base, altura));
        }
        else if (Rombo){
            lado = Integer.parseInt(TextoA.getText());
            Dmayor = Integer.parseInt(TextoB.getText());
            Dmenor = Integer.parseInt(TextoC.getText());
            area = CRombo.CalcularArea(Dmayor, Dmenor);
            perimetro = CRombo.CalcularPerimetro(lado);
            Area.setText("Area = "+String.valueOf(area));
            Perimetro.setText("Perimetro = "+String.valueOf(perimetro));
        }
        else{
            altura = Integer.parseInt(TextoA.getText());
            lado =  Integer.parseInt(TextoB.getText());
            Bmayor = Integer.parseInt(TextoC.getText());
            Bmenor = Integer.parseInt(TextoD.getText());
            area = CTrapecio.CalcularArea(altura, Bmayor, Bmenor);
            perimetro = CTrapecio.CalcularPerimetro(Bmayor, Bmenor, lado);
            Area.setText("Area = "+String.valueOf(area));
            Perimetro.setText("Perimetro = "+String.valueOf(perimetro));
        }
    }//GEN-LAST:event_BCalcularActionPerformed

    private void TextoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoCActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TextoCActionPerformed

    private void TextoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel Area;
    private javax.swing.JLabel B;
    private javax.swing.JButton BBorrar;
    private javax.swing.JButton BCalcular;
    private javax.swing.JButton BSalir;
    private javax.swing.JLabel C;
    private javax.swing.JLabel D;
    private javax.swing.JLabel Figura;
    private javax.swing.JLabel Hipotenusa;
    private javax.swing.JLabel Instrucciones;
    private javax.swing.JMenuItem MCirculo;
    private javax.swing.JMenuItem MCuadrado;
    private javax.swing.JMenuItem MRectangulo;
    private javax.swing.JMenuItem MRombo;
    private javax.swing.JMenuItem MTR;
    private javax.swing.JMenuItem MTrapecio;
    private javax.swing.JLabel Perimetro;
    private javax.swing.JTextField TextoA;
    private javax.swing.JTextField TextoB;
    private javax.swing.JTextField TextoC;
    private javax.swing.JTextField TextoD;
    private javax.swing.JLabel TipoTriangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
